### ISSUE TITLE
Any chance for a PPA?

### ISSUE THREAD

**Issue by dandv** [RedHatter/finalterm-reborn#10]
I've trued to make the project, but it requires a bunch of dependencies that as a casual user I'm having trouble finding and installing.

**Comment by RedHatter** [comment]
I'll spend the time getting a ppa setup when the core (vt220 emulation) is done.

But for now I'll build a quick checkinstall deb for you. I'll see if I can get that done tomorrow.

**Comment by RedHatter** [comment]
You can download the deb in the [releases](https://github.com/RedHatter/finalterm-reborn/releases) section.

Note: As it says on the page this is not meant to be thought of as a _release_. It's more of a preview.
