### ISSUE TITLE
major compilation errors

### ISSUE THREAD

**Issue by SolarAquarion** [RedHatter/finalterm-reborn#15]
[  3%] Generating src/FinalTerm.c, src/Terminal.c, src/TerminalStream.c, src/Encoder.c, src/TerminalOutput.c, src/CharacterAttributes.c, src/TerminalView.c, src/TextView.c, src/TerminalWidget.c, src/NestingContainer.c, src/Autocompletion.c, src/NotifyingList.c, src/ScrollableTreeView.c, src/Utilities.c, src/SettingsWindow.c, src/TextMenu.c, src/ColorScheme.c, src/Theme.c, src/KeyBindings.c, src/Command.c, src/Settings.c, src/Metrics.c, src/StatusBar.c
    unity.vapi:97.4-97.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
    /home/solaraquarion/finalterm-reborn/src/Utilities.vala:102.3-102.27: warning: Gtk.Widget.override_font has been deprecated since 3.16
    /home/solaraquarion/finalterm-reborn/src/Command.vala:110.28-110.87: warning: unhandled error `GLib.RegexError'
    				substitute_parameter = placeholder_pattern.replace(substitute_parameter, -1, 0, "");
    				                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    /home/solaraquarion/finalterm-reborn/src/ScrollableTreeView.vala:88.18-88.21: error: Argument 1: Cannot pass value to reference or output parameter
    			model.remove (iter);
    			              ^^^^
    /home/solaraquarion/finalterm-reborn/src/Settings.vala:293.3-293.40: warning: unhandled error `GLib.Error'
    		style.load_from_data (css, css.length);
    		^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    /home/solaraquarion/finalterm-reborn/src/TerminalOutput.vala:1068.14-1068.24: warning: unhandled error `GLib.RegexError'
    				} while (info.next());
    				         ^^^^^^^^^^^
    /home/solaraquarion/finalterm-reborn/src/TerminalOutput.vala:120.3-120.61: error: Assignment: Cannot convert from `Gee.HashMap<Gtk.TextTag,TextMenu>' to `Gee.Map<TextMenu,Gtk.TextTag>'
    		tags_by_text_menu = new Gee.HashMap<Gtk.TextTag,TextMenu>();
    		^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    /home/solaraquarion/finalterm-reborn/src/TerminalView.vala:253.3-253.45: warning: Gtk.Widget.override_background_color has been deprecated since 3.16
    /home/solaraquarion/finalterm-reborn/src/Terminal.vala:64.12-64.57: warning: unhandled error `GLib.FileError'
    				return FileUtils.read_link(@"/proc/$(entry.key)/cwd");
    				       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    /home/solaraquarion/finalterm-reborn/src/Terminal.vala:256.6-256.50: warning: unhandled error `GLib.IOChannelError'
    					this_terminal.command_channel.shutdown(false);
    					^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    /home/solaraquarion/finalterm-reborn/src/Terminal.vala:71.3-71.83: warning: unhandled error `GLib.SpawnError'
    		Process.spawn_command_line_sync ("sh -c 'cat /proc/*/stat'", out stat, out error);
    		^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    /home/solaraquarion/finalterm-reborn/src/Terminal.vala:91.3-91.83: warning: unhandled error `GLib.SpawnError'
    		Process.spawn_command_line_sync ("sh -c 'cat /proc/*/stat'", out stat, out error);
    		^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    /home/solaraquarion/finalterm-reborn/src/SettingsWindow.vala:29.15-29.23: warning: Gtk.Stock has been deprecated since 3.10
    /home/solaraquarion/finalterm-reborn/src/FinalTerm.vala:415.5-415.43: warning: Gdk.Screen.get_monitor_geometry has been deprecated since 3.22
    /home/solaraquarion/finalterm-reborn/src/FinalTerm.vala:415.45-415.82: warning: Gdk.Screen.get_primary_monitor has been deprecated since 3.22
    /home/solaraquarion/finalterm-reborn/src/NestingContainer.vala:392.4-400.13: warning: unhandled error `GLib.Error'
    Compilation failed: 2 error(s), 14 warning(s)

**Comment by bjorn3** [comment]
I don't think this is maintained anymore. :(
