### ISSUE TITLE
Graphics Issues

### ISSUE THREAD

**Issue by s5bug** [RedHatter/finalterm-reborn#6]
When deleting, deleted character appears after the block.

On the license agreement thingies, the walls are mate of letters instead of symbols, and pressing left only glitches the thing out more.

**Comment by RedHatter** [comment]
Can you point me to an example of a "license agreement thingy"?

**Comment by RedHatter** [comment]
Possibly fixed in 739828313049e17c8304188582b793d24f802b76. Can you verify?

**Comment by RedHatter** [comment]
Closing for lack of reply.
